# Generated by Django 2.2.3 on 2020-05-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20200506_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evalution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon'),
        ),
    ]
